[tool.poetry]
name = "axe-core-python"
version = "0.1.0"
description = ""
authors = ["Ruslan Iskov <ruslan.rv.ua@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
black = {version = "^22.6.0", allow-prereleases = true}
selenium = "^4.4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
