name: Python checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test with Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          python_version: ["3.9", "3.10", "3.11"]
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3
          uses: actions/setup-python@v3
          with:
            python-version: ${{ matrix.python_version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install
        - name: Lint with ruff
          run: ruff .
        - name: Check formatting with black
          run: black . --check --verbose
        - name: Run unit tests
          run: |
            poetry run pytest